PracticeApplication/PracticeApplication/Models/ComposerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PracticeApplication.Models
{
    public class ComposerViewModel
    {
        public string Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Date of Birth")]
        public DateTime? Birthdate { get; set; }

        [Display(Name = "Date of Death")]
        public DateTime? Died { get; set; }

        public List<PieceViewModel> Pieces { get; set; }
    }
}

PracticeApplication/PracticeApplication/Models/ErrorViewModel.cs
namespace PracticeApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticeApplication/PracticeApplication/Models/PieceViewModel.cs
using System;

namespace PracticeApplication.Models
{
    public class PieceViewModel
    {
        public string Id { get; set; }
        public string ComposerId { get; set; }
        public string Title { get; set; }
        public DateTime Date { get; set; }
    }
}

PracticeApplication/PracticeApplication/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeApplication.Models;
using PracticeApplication.Orchestrator.Interface;
using System.Collections.Generic;

namespace PracticeApplication.Controllers
{
    public class LibraryController : Controller
    {
        private ILibraryOrchestrator _orchestrator;

        public LibraryController(ILibraryOrchestrator orchestrator)
        {
            _orchestrator = orchestrator;
        }

        public IActionResult ComposerIndex()
        {
            List<ComposerViewModel> models = _orchestrator.GetAllComposers();
            return View(models);
        }

        public IActionResult ComposerDetail(string id)
        {
            ComposerViewModel model = _orchestrator.GetComposer(id);
            return View(model);
        }

        public IActionResult AddComposer()
        {
            ComposerViewModel model = new ComposerViewModel();
            return View(model);
        }

        //TODO: call orchestrator to save model and return id
        [HttpPost]
        public IActionResult AddComposer(ComposerViewModel model)
        {
            string newComposerId = _orchestrator.AddComposer(model);
            return RedirectToAction("ComposerDetail", new { id = newComposerId });
        }
    }
}

PracticeApplication/PracticeApplication/Views/Library/AddComposer.cshtml
@using PracticeApplication.Extensions
@model PracticeApplication.Models.ComposerViewModel

@{
    ViewData["Title"] = "AddComposer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AddComposer</h1>

<h4>ComposerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddComposer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" type="hidden"/>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthdate" class="control-label"></label>
                <input asp-for="Birthdate" class="form-control" value="@Model.Birthdate.ToShortDate()"/>
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Died" class="control-label"></label>
                <input asp-for="Died" class="form-control" value="@Model.Died.ToShortDate()"/>
                <span asp-validation-for="Died" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PracticeApplication/PracticeApplication/Views/Library/ComposerDetail.cshtml
@model PracticeApplication.Models.ComposerViewModel

@{
    ViewData["Title"] = "ComposerDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.LastName, @Model.FirstName</h1>

<div>
    <div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Birthdate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Birthdate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Died)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Died)
            </dd>
        </dl>
    </div>
    <hr />
    <div>
        @if (Model.Pieces != null)
        {
            @for (int i = 0; i < Model.Pieces.Count; i++)
            {
                PieceViewModel piece = Model.Pieces[i];
                <p>@Html.ActionLink($"{piece.Title} - {piece.Date.ToShortDateString()}", "ComposerIndex", "Library")</p>
            }
        }

    </div>
</div>

PracticeApplication/PracticeApplication/Views/Library/ComposerIndex.cshtml
@using PracticeApplication.Extensions
@using PracticeApplication.Models
@model List<ComposerViewModel>

@{
    ViewData["Title"] = "Your Library - Composer Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h1>Composer Index</h1>
    @foreach (ComposerViewModel m in Model)
    {
        <div>
            <h2>@Html.ActionLink($"{@m.LastName}, {@m.FirstName}", "ComposerDetail", new { id = m.Id })</h2>
            <p>@m.Birthdate.ToShortDate() - @m.Died.ToShortDate()</p>
        </div>
    }
    <div>
        @Html.ActionLink("Add Composer to Library", "AddComposer")
    </div>
</div>

PracticeApplication/PracticeApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticeApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticeApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PracticeApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>